version: '3.4'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: contactlist
      MYSQL_USER: root
    volumes:
      - d:/mydata:/var/lib/mysql
    ports:
      - 3307:3306
  ginexample:
    image: ginexample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE=root:mysql123@tcp(db:3306)/contactlist?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - db
    ports:
      - 8080:8080
